### ISSUE TITLE
Comment on Github Pull Requests

### ISSUE THREAD

**Issue by giggio** [coveralls-net/coveralls.net#12] opened 2015-02-23 13:27 UTC
It seems that Coveralls.io is able to comment on PRs from Github, but this library does not yet support it.
I asked the guys at coveralls, and they said the library to implement a few things. Checkout https://github.com/lemurheavy/coveralls-public/issues/429#issuecomment-75455356
It seems you have to send the PR number: https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference

**Comment by jdeering** [comment] 2015-02-23 18:46
This has been added. Be aware that, when using AppVeyor, pull requests **do not** decrypt secure environment variables. If COVERALLS_REPO_TOKEN is set as a configured environment variable (either in yml or in UI) and it's encrypted, calls to coveralls won't work.

**Comment by giggio** [comment] 2015-02-23 19:36
Right... How to solve this? Any idea?

**Comment by jdeering** [comment] 2015-02-23 20:20
- Don't use yml for configuration and stick strictly to AppVeyor's UI for setting up your builds. Set the environment variable with your token unencrypted.
- Ask AppVeyor to change how this works.
- Use a different CI service. 

I'm planning to personally research other available CI options for my own personal use as well as to provide support for this project across more platforms.

**Comment by FeodorFitsner** [comment] 2015-02-26 19:11
I've checked `coveralls.net` utility and I think it would be pretty easy to add "native" support for it into AppVeyor. We could have like a new `coveralls` section in `appveyor.yml`. This way it will work in both regular and PR builds (adding another deployment provider won't work as deployment is also disabled for PR builds).

**Comment by jasondeering** [comment] 2015-02-26 19:21
Works for me. Let me know if there's anything I can do to help with this.

**Comment by jdeering** [comment] 2015-02-26 19:22
Works for me. Let me know if there's anything I can do to help with this.

**Comment by FeodorFitsner** [comment] 2015-02-26 19:56
Cool, thanks!

**Comment by giggio** [comment] 2015-02-26 20:52
@FeodorFitsner That would be awesome!

**Comment by gep13** [comment] 2015-03-17 19:37
So, having just recently set up Coveralls for a small project that I am working on, I was curious about this ability to comment on GitHub.  Are we saying that I can't use an environment variable to do this work?  If so, can I use settings both from the UI and from my YAML?  What is the state of this from an AppVeyor point of view @FeodorFitsner ?

Thanks!

**Comment by FeodorFitsner** [comment] 2015-03-18 05:34
So, we agreed on adding built-in support for coveralls, but I can't give you an ETA yet.
Yes, you can define vars on both UI and in YAML.

**Comment by gep13** [comment] 2015-03-18 07:06
So, in theory, assuming that I add the Coveralls token to the AppVeyor UI, I should currently get commenting on Pull Requests when using this application to publish to coveralls.  Is that right? /cc @jdeering

**Comment by FeodorFitsner** [comment] 2015-03-18 07:28
Yes, unless it's unencrypted it will be merged into vars defined in yml and available in PR build. But again, anyone with bad intentions could steal it by submitting PR listing all environment variables.

**Comment by gep13** [comment] 2015-03-18 07:32
> @FeodorFitsner said...
> anyone with bad intentions could steal it by submitting PR listing all environment variables.

Yip, valid point. :+1+  Right now, it is not an essential addition for me, only just got Coveralls and Coverity set up on my small project, and was curious when I saw this feature within Coveralls.

**Comment by TerribleDev** [comment] 2015-04-22 03:12
:+1: on this as well

**Comment by clairernovotny** [comment] 2016-08-16 18:25
@FeodorFitsner any updates on this -- on figuring out a secure way to make this work for PR's?

**Comment by FeodorFitsner** [comment] 2016-08-16 19:38
Actually, there is a new option `Enable secure variables in Pull Requests from the same repository only` (on General tab of AppVeyor project settings) that is available for both public and private projects and may work for this case.

**Comment by clairernovotny** [comment] 2016-08-16 19:39
@FeodorFitsner is that something I need to configure in the AppVeyor.yml or only in the UI?

**Comment by FeodorFitsner** [comment] 2016-08-16 19:40
It's UI only.

**Comment by clairernovotny** [comment] 2016-08-26 03:30
@FeodorFitsner The UI option works great for PR's from branches that are in the same repo, as designed, but it still leaves a gap for PR's from external contributors.

I suspect that the only secure way to do it would be or AppVeyor to provide its own coveralls.net binary and invoke it as part of a separate dedicated step and pass the `repo-token` parameter directly. That'd prevent exposure to scripts/items in the PR itself.

Any chance of that happening?

**Comment by jdeering** [comment] 2017-07-18 15:30
This issue is primarily related to functionality in AppVeyor itself and not related to the `coveralls.net` tools as they are currently implemented.

**Closed as completed by jdeering** 2017-07-18 15:30 UTC
